import Head from "next/head";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="flex flex-col mx-auto w-11/12 justify-center items-center">
        <h1 className="text-center font-bold text-3xl mb-8">News App</h1>
        <p className="text-gray-800 text-center text-xl leading-relaxed border rounded-2xl p-10">
          👋 Welcome to this 📰 news app created by{" "}
          <a href="https://charleskrook.io/">Charles</a>. <br />
          I 🔧 this app using Server Side Rendering with NextJS.
          <br />
          Head over to the{" "}
          <a href="https://github.com/ckrook/News-App">github</a> repo if you
          want to 👀 at the code.
        </p>
      </div>
    </div>
  );
}
