import Head from "next/head";
import Nav from "../components/Nav";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex mx-auto w-11/12 justify-center">
        <header className="py-8">
          <h1 className="mb-4 text-center font-bold text-3xl">News App</h1>

          <Nav />
        </header>
      </div>
    </div>
  );
}
