import Head from "next/head";
import React from "react";
import Header from "../../components/Header";
import { useRouter } from "next/router";

function Feed({ pageNumber, articles }) {
  const router = useRouter();
  return (
    <>
      <div>
        <Head>
          <title>News App - feed</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className="flex flex-col w-10/12 m-auto justify-center">
          {articles.map((article, index) => (
            <div
              key={index}
              className="text-center border-b-4 border-black mb-8 pb-8"
            >
              <h1
                onClick={() => (window.location.href = article.url)}
                className="cursor-pointer font-semibold text-2xl mb-2"
              >
                {article.title}
              </h1>
              <p className="mb-4">{article.description}</p>
              {!!article.urlToImage && (
                <img
                  onClick={() => (window.location.href = article.url)}
                  className="m-auto cursor-pointer "
                  src={article.urlToImage}
                  alt={article.title}
                />
              )}
            </div>
          ))}
        </main>
        <div className="flex justify-center space-x-6 py-8">
          <div
            onClick={() => {
              if (pageNumber > 1) {
                router.push(`/feed/${pageNumber - 1}`);
              }
            }}
            className={pageNumber === 1 ? "disable" : "active"}
          >
            previous page
          </div>
          <div>{pageNumber}</div>
          <div
            onClick={() => {
              if (pageNumber < 5) {
                router.push(`/feed/${pageNumber + 1}`);
              }
            }}
            className={pageNumber === 1 ? "disable" : "active"}
          >
            Next page
          </div>
        </div>
      </div>
    </>
  );
}

export const getServerSideProps = async (pageContext) => {
  const pageNumber = pageContext.query.id;

  if (!pageNumber || pageNumber < 1 || pageNumber > 5) {
    return {
      props: {
        articles: [],
        pageNumber: 1,
      },
    };
  }

  const apiResponse = await fetch(
    `
    https://newsapi.org/v2/top-headlines?country=us&pageSize=5&page=${pageNumber}
  `,
    {
      headers: {
        Authorization: `Bearer ${process.env.NEXT_PUBLIC_NEWS_KEY}`,
      },
    }
  );
  const apiJson = await apiResponse.json();

  const { articles } = apiJson;

  return {
    props: {
      articles,
      pageNumber: Number.parseInt(pageNumber),
    },
  };
};

export default Feed;
